apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trips    
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - image: registryxaj9926.azurecr.io/tripinsights/trips:latest
        name: trips
        ports:
          - containerPort: 80
        envFrom:
          - configMapRef:
              name: trip-config
        resources: {}
        terminationMessagePath: /termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30   
         